# Generated by Django 6.0.3 on 2026-04-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
